### ISSUE TITLE
Large memory consumption

### ISSUE THREAD

**Issue by alpxp** [omgovich/colord#100]
I have a large memory consumption. It starts from a few mb, but goes to a few Gb in about 24h. 

```
● colord.service - Manage, Install and Generate Color Profiles
     Loaded: loaded (/lib/systemd/system/colord.service; static)
     Active: active (running) since Sat 2023-03-18 17:09:14 CET; 16h ago
   Main PID: 1432 (colord)
      Tasks: 3 (limit: 18908)
     Memory: 1.4G
        CPU: 4min 20.780s
     CGroup: /system.slice/colord.service
             └─1432 /usr/libexec/colord
```
I'm one fresh Ubuntu 22.04 (same behaviour on ubuntu 20.04) with a bunch of dockers.
`Linux alpxp-nuc 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
`

How can I debug what is going on? What logs should I check?

**Comment by ludofischer** [comment]
Your issue is related to a completely different project with the same name:  [colord from the freedesktop project](https://www.freedesktop.org/software/colord/index.html).

**Comment by alpxp** [comment]
oops. sorry )
