### ISSUE TITLE
Proofreading wanted

### ISSUE THREAD

**Issue by omgovich** [omgovich/colord#14]
Hi, my open-source buddies!
Unfortunately, my coding skills are way better than my English 😅
The README became huge and it would be cool if somebody checks and improves the texts there.

@molefrog and @rschristian hope you guys have time to help me a bit 🙏

**Comment by rschristian** [comment]
I think it reads great! Just a couple small items stood out, not sure they need to be changed, but I'll open a PR for discussion

**Comment by omgovich** [comment]
Thanks, guys! ❤️
