### ISSUE TITLE
CommonJS exports

### ISSUE THREAD

**Issue by kripod** [omgovich/colord#15]
While it’s a very progressive approach to only offer ESM exports, I think that CommonJS should be supported too via [package entry points](https://nodejs.org/api/packages.html#packages_package_entry_points), e.g. when used in files ran by Node (e.g. for color manipulation inside `tailwind.config.js`).

One of my more recent projects offer the following entry points as an example: https://github.com/kripod/otion/blob/18eea38e49d92c86ff8144fecc6404ebac0fa3ac/packages/otion/package.json#L24-L39

**Comment by omgovich** [comment]
You're right. Don't like creating file bundle copies, but to cover all kind of the projects we have to do that.

**Comment by omgovich** [comment]
Ooof. It seems to me that it's not possible to keep plugins in `/dist/plugin` subfolder while supporting Node less than 12.7.
Looks like I have to publish `dist` folder since older Node versions do not support `exports` field and I don't see any other way to say legacy Node that `require('colord/plugins/names')` is actually require('colord/dist/plugins/names').

**Comment by omgovich** [comment]
```
  "main": "./dist/index.cjs",
  "module": "./dist/index.mjs",

  // Not supported by Node 12-, so legacy Node apps won't be able to require a plugin =(
  "exports": {
    ".": {
      "import": "./dist/index.mjs",
      "require": "./dist/index.cjs"
    },
    "./plugins/*": {
      "import": "./dist/plugins/*.mjs",
      "require": "./dist/plugins/*.cjs"
    }
  },
```

**Comment by omgovich** [comment]
God, I hate those copy-package-json-to-dist-and-publish it tricks =)

**Comment by omgovich** [comment]
Hey @kripod! I just released `v0.9` with CJS files included. Works well on my local Node env.
Would be glad if you'll test the new version too 🙏

**Comment by omgovich** [comment]
![image](https://user-images.githubusercontent.com/206567/113850002-af829980-97a2-11eb-82c7-7f7dda4a2241.png)

**Comment by kripod** [comment]
> Hey @kripod! I just released `v0.9` with CJS files included. Works well on my local Node env.
> Would be glad if you'll test the new version too 🙏

Thank you, it works perfectly! 😊

**Comment by omgovich** [comment]
Hi, thanks! Have you tested 0.9.0 or 0.9.1?
I recently published the new version which has updated export.

**Comment by kripod** [comment]
v0.9.1 was the one that worked fine, I haven’t tested v0.9.0.

**Comment by omgovich** [comment]
Thanks! You helped a lot.
I think we are almost ready to v1 :)
