### ISSUE TITLE
Add Double Split Complementary Color Harmony

### ISSUE THREAD

**Issue by lbragile** [omgovich/colord#68]
The Harmonies plugin seems to be [missing](https://github.com/omgovich/colord/blob/master/src/plugins/harmonies.ts#L3) the [double split complementary](https://color.adobe.com/create/color-wheel) color harmony.

I think it will be a great addition and should be simple to add as it is just a `[-30, 0, 30, 150, 210]` rotation array.

**Comment by omgovich** [comment]
Hi! Thanks for the issue!

@EricRovell could I ask to add this one to the `harmonies` plugin?

**Comment by EricRovell** [comment]
@omgovich Yes, I will do it :)
Thank you, @lbragile

**Comment by omgovich** [comment]
Closed via #69

**Comment by omgovich** [comment]
Available in v2.6. Thanks, guys!
