### ISSUE TITLE
Color perceived difference

### ISSUE THREAD

**Issue by EricRovell** [omgovich/colord#74]
Hi, it is me again :)

Found out about [color perceived difference](https://zschuessler.github.io/DeltaE/learn/) and I was thinking, would it be a good addition for `colord`? Seems like it could be used to extend the `LAB plugin`.

**Comment by omgovich** [comment]
Hi! It's super funny that you proposed this functionality since I read about Dela E just yesterday :)

I like the idea and think it might fit well as part as lab plugin, so I will be glad to see it here :)

**Comment by EricRovell** [comment]
Ha, that's fun :)
I think I will begin to work on the extension in a couple of days then :)

**Comment by omgovich** [comment]
Went to a conference a few days ago and met a developer from Yandex who asked about this functionality.
So we're definitely on the right track =))

**Comment by EricRovell** [comment]
Feels good to find a useful functionality! I am busy a bit these days, but I will manage to do it in reasonable time! 😉

**Comment by EricRovell** [comment]
@omgovich I have implemented functions for `Delta E76`, `Delta E94`, `Delta E2000`. I wonder, do we need all this implementations or do you think we should provide only the latest one?

**Comment by omgovich** [comment]
It seems like `Delta E 2000` is the most valid one, so we can provide just this one.

**Comment by EricRovell** [comment]
@omgovich I spend a lot of time today on this problem. I guess it works, tested for values [here](https://cielab.xyz/colordiff.php). But the problem is, it always gave a bit another result. I was testing LAB/LAB comparison and... well, internal color is RGB. Even if I construct an instance, it converts to RGB for the state!

The problem is as RGB values are discrete, while (for example) LAB is continuous. We lost some accuracy (maybe a lot).

I had an idea to incapsulate the inner rgb state as float values to save accuracy and return integer values only for end consumer, not for inner conversions.

P.S. Right now I am working and testing the Delta E 2000 in my package, it may be a problem of my code.

**Comment by EricRovell** [comment]
Feature is ready and merged #77 😸
