### ISSUE TITLE
Retain Hue & Saturation at Light Max & Min

### ISSUE THREAD

**Issue by 2manypistachios** [omgovich/colord#75]
I ran into an issue where my users could control a color wheel, and control the lightness level separately from hue and saturation. If they were to go absolute white or absolute dark, then they would lose their hue and saturation values. It creates a fairly jarring effect on the app.

![Animation](https://user-images.githubusercontent.com/33584960/132603738-d7a87476-4cc5-4386-94dd-264bc0a4b165.gif)

Would appreciate some advice.

**Comment by omgovich** [comment]
Hi, I would say it's a common problem that every color picker developer faces.
Just check a saturation of new color and if it's `0` ot `100` — don't change an internal `hue` value.
I guess you might find a solution, for example, in `react-color` package code.
