### ISSUE TITLE
hue changed to zero

### ISSUE THREAD

**Issue by georggrubner** [omgovich/colord#81]
When creating an hsl object with a specific hue, but saturation an lightness set to 0, the hue will also be set to zero

test case:

```es6
expect(colord({ h: 50, s: 0, l: 0 }).toHsl().h).toBe(50)
```

this test will fail and the received result. The expected result is, that the hue stays the same.

**Comment by omgovich** [comment]
Hi! Not sure it's a bug: a color with no saturation and lightness is black.
Black doesn't have any hue since... you know... it's black :)

**Comment by georggrubner** [comment]
Well, we use colord for our color picker. As you can see, when you change the hue, color panel should change. This is only possible if we know the hue.

![colorpicker](https://user-images.githubusercontent.com/24992489/142882238-9cc8cab3-eba1-4d1c-a556-65dd7cf57421.gif)

We had to implement a fix on our side, where we override the hue manually on the object colord gives us. This extra step should not be necessary. An HSL object passed to the colrd function should always be the same as the one we receive when calling `toHsl()`

**Comment by omgovich** [comment]
As a developer of a color picker component, I would highly recommend storing the current hue in a separate variable.

You can't rely on color conversion libraries here since white, black and any grayscale color could break the conversion between color spaces.

**Comment by georggrubner** [comment]
This makes sense. Thanks for you help!
