### ISSUE TITLE
Exports map in package breaks when using with vite

### ISSUE THREAD

**Issue by madeleineostoja** [omgovich/colord#83]
When trying to import `colord` with [Vite ](https://vitejs.dev/) (via [Sveltekit](https://kit.svelte.dev/)), the bundler throws the following error:

```js
import { colord } from 'colord';
```

```sh
Internal server error: Missing "./package.json" export in "colord" package
```

Not entirely sure what's going on but on the surface of it it looks like Vite requires access to the package's `package.json` for analysis, and since it's not exposed via `exports` it's throwing an error

**Comment by omgovich** [comment]
Hi! Yeah, you're rightP: we need to add package.json to "exports" field. Going to fix that as soon as I have time.

P.S. PR are also welcome :)

**Comment by omgovich** [comment]
Hey! Just released `v2.9.2`. Everything should be good now.

**Comment by omgovich** [comment]
Please let me know about the results: if it helps I would add the same fix to all my packages.

**Comment by madeleineostoja** [comment]
Yep that fixes Vite compat, thanks!
