### ISSUE TITLE
TypeScript 4.7 - Add missing ESM `types` subpath export condition

### ISSUE THREAD

**Issue by scott-lc** [omgovich/colord#94]
The TypeScript 4.7 `NodeNext` module resolver does not honor the legacy `types` property in the `package.json` file.  You need to add a `types` export condition as described [here](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing).

> Note that the "types" condition should always come first in "exports".

With this change, your `package.json` exports should look something like:

```jsonc
{
  // ...
  "exports": {
    ".": {
      "types": "./index.d.ts",      // <-- Add this
      "import": "./index.mjs",
      "require": "./index.js",
      "default": "./index.mjs"
    },
    "./plugins/a11y": {
      "types": "./plugins/a11y.d.ts",   // And this
      "import": "./plugins/a11y.mjs",
      "require": "./plugins/a11y.js",
      "default": "./plugins/a11y.mjs"
    },
    // ...
    "./plugins/xyz": {
      "types": "./plugins/xyz.d.ts",    // etc.
      "import": "./plugins/xyz.mjs",
      "require": "./plugins/xyz.js",
      "default": "./plugins/xyz.mjs"
    }
  }
}

**Comment by omgovich** [comment]
Hi! Thanks for reporting! @pkishorez made a fix and I released it in v2.9.3
